version: "3"
services:
  streamlit:
    build: .
    command: "streamlit run src/dashboard.py"
    env:
      - GOOGLE_APPLICATION_CREDENTIALS: "/usr/src/app/resources/YOUR_SECRET_KEY_FILE"
      - SECRET_NAME: "YOUR_SECRET_NAME"
    ports:
      - "8501:8501"
    volumes:
      - "./src:/usr/src/app/src"
      - "./resources:/usr/src/app/resources:ro"
